version: '3'
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: web-app
    container_name: web-app
    tty: true
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    restart: always
    container_name: web-webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    container_name: postgres-web
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admpass'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - app-network

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile_py
    restart: always
    volumes:
      - ./djangoproj/:/var/www/djangoproj
    ports:
      - "8000:8000"
    command: "python manage.py runserver 192.168.99.100:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge