# Generated by Django 4.0 on 2022-12-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Price', models.IntegerField(default=300)),
                ('ImageURL', models.CharField(max_length=200, null=True)),
                ('Discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Cart', models.IntegerField(default=0)),
                ('Bookmarks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WishBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorodapi.books')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorodapi.users')),
            ],
        ),
        migrations.CreateModel(
            name='CartBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorodapi.books')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorodapi.users')),
            ],
        ),
    ]
